sudo: required
dist: trusty
language: csharp
mono: beta

# Install .NET v3.5 profile
before_install:
  - MONO_PATH=`echo /opt/mono/lib/mono` && sudo ln -s $TRAVIS_BUILD_DIR/Mono/2.0 $MONO_PATH/2.0
  - sudo ln -s $TRAVIS_BUILD_DIR/Mono/xbuild-frameworks/.NETFramework/v3.5 $MONO_PATH/xbuild-frameworks/.NETFramework/v3.5

# Add build number to version
before_script: 
  - sed -ri "s/VersionNumber\((.*), 0\)/VersionNumber(\1, $TRAVIS_BUILD_NUMBER)/g" Oxide.Core/OxideMod.cs
  - find . -name "*Extension.cs" -exec sed -ri "s/VersionNumber\((.*), 0\)/VersionNumber(\1, $TRAVIS_BUILD_NUMBER)/g" {} \;

# Build the project
solution: Oxide.sln

# Run deployment script
after_success: [[ $TRAVIS_REPO_SLUG == OxideMod/Oxide ]] && [[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_BRANCH == master ]] && ./deploy.sh

notifications:
  email: false
  slack:
    rooms:
      secure: "rhZ/ZlRhJWfRWquzilEGrgSvG5aV8FaPAPXsiMQQCwP+bjNiOH6siYsm7L0Lqv6no1YQSsCpO2b/DO60DMMJRUpdxBgfdHkT9ioxHJiA4i4ObXEpQOu3qKvRvTKD+pLnYGCghXI6MjtTPZnHDuwaErzg1tOc52t7Z4C+renLfY0="

env:
  global:
    - secure: "Xl3Pwx7OtKTo8JdQI5aReKoSdVOLGpvIF/JWhxQMnUWzfB0olO71HF/KHh1mUDWPI6cOaQrQJ+4d/dtMLMUTJgTnYK1lOsF4d+Y5UsNRb1/Cq1sgvs/xEzcT9zhinLeuGUmjsJK2vTqat6QcvZbErlwBoGZSOMkX4BYsR8QFbpU="
