language: csharp

# Update Mono to latest snapshot
before_install:
  - echo "deb http://jenkins.mono-project.com/repo/debian sid main" | sudo tee /etc/apt/sources.list.d/mono-jenkins.list
  - sudo apt-get update -qq && sudo apt-get install -y mono-4.0-snapshot-latest && . mono-snapshot mono-4.0
  - MONO_PATH=`echo /opt/mono-*/lib/mono` && sudo ln -s $TRAVIS_BUILD_DIR/Mono/2.0 $MONO_PATH/2.0 && sudo ln -s $TRAVIS_BUILD_DIR/Mono/xbuild-frameworks/.NETFramework/v3.5 $MONO_PATH/xbuild-frameworks/.NETFramework/v3.5

# Add build number to version
before_script: 
  - sed -ri "s/VersionNumber\((.*), 0\)/VersionNumber(\1, $TRAVIS_BUILD_NUMBER)/g" Oxide.Core/OxideMod.cs
  - for file in */ ; do file="${file%/*}"; file="$file/${file##*.}Extension.cs"; if [[ -e "$file" ]]; then sed -ri "s/VersionNumber\((.*), 0\)/VersionNumber(\1, $TRAVIS_BUILD_NUMBER)/g" "$file"; fi done

# Build the project
solution: Oxide.sln

# Run deployment script
after_success: "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == OxideMod/Oxide ]] && [[ $TRAVIS_BRANCH == master ]] && ./deploy.sh"

notifications:
  email: false
  slack:
    rooms:
      secure: "bmk8bmBzIOjuCR4qs5zx+SypIqLFR0QqXmd04mUohaLpAp1lJ5JQiOgKAcQPz0sqdUlu2ZAWjDT2brx0/DPssBJnQOTdKcWhYdp6n70oqXA/tvSj0FLSrZyFJjldI5okqkqGXkOdaees5mqWxEYVJEP/BjgVsDd+JvTuV5jGXlc="

env:
  global:
    - secure: "rhZ/ZlRhJWfRWquzilEGrgSvG5aV8FaPAPXsiMQQCwP+bjNiOH6siYsm7L0Lqv6no1YQSsCpO2b/DO60DMMJRUpdxBgfdHkT9ioxHJiA4i4ObXEpQOu3qKvRvTKD+pLnYGCghXI6MjtTPZnHDuwaErzg1tOc52t7Z4C+renLfY0="
