language: csharp

# Update Mono to latest snapshot
before_install:
  - echo "deb http://jenkins.mono-project.com/repo/debian sid main" | sudo tee /etc/apt/sources.list.d/mono-jenkins.list
  - sudo apt-get update -qq && sudo apt-get install -y mono-4.0-snapshot-latest && . mono-snapshot mono-4.0
  - MONO_PATH=`echo /opt/mono-*/lib/mono` && sudo ln -s $TRAVIS_BUILD_DIR/Mono/2.0 $MONO_PATH/2.0 && sudo ln -s $TRAVIS_BUILD_DIR/Mono/xbuild-frameworks/.NETFramework/v3.5 $MONO_PATH/xbuild-frameworks/.NETFramework/v3.5

# Add build number to version
before_script: 
  - sed -ri "s/VersionNumber\((.*), 0\)/VersionNumber(\1, $TRAVIS_BUILD_NUMBER)/g" Oxide.Core/OxideMod.cs
  - for file in */ ; do file="${file%/*}"; file="$file/${file##*.}Extension.cs"; if [[ -e "$file" ]]; then sed -ri "s/VersionNumber\((.*), 0\)/VersionNumber(\1, $TRAVIS_BUILD_NUMBER)/g" "$file"; fi done

# Build the project
solution: Oxide.sln

# Run deployment script
after_success: "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == OxideMod/Oxide ]] && [[ $TRAVIS_BRANCH == master ]] && ./deploy.sh"

notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  # Slack (oxidemod.slack.com)
  slack:
    rooms:
      secure: "bmk8bmBzIOjuCR4qs5zx+SypIqLFR0QqXmd04mUohaLpAp1lJ5JQiOgKAcQPz0sqdUlu2ZAWjDT2brx0/DPssBJnQOTdKcWhYdp6n70oqXA/tvSj0FLSrZyFJjldI5okqkqGXkOdaees5mqWxEYVJEP/BjgVsDd+JvTuV5jGXlc="

# Environmental system variables
env:
  global:
    # Super secure, encrypted variables! Ssssh!
    - secure: "Xl3Pwx7OtKTo8JdQI5aReKoSdVOLGpvIF/JWhxQMnUWzfB0olO71HF/KHh1mUDWPI6cOaQrQJ+4d/dtMLMUTJgTnYK1lOsF4d+Y5UsNRb1/Cq1sgvs/xEzcT9zhinLeuGUmjsJK2vTqat6QcvZbErlwBoGZSOMkX4BYsR8QFbpU="
